name = "smoke"
compatibility_date = "2025-07-18"
main = "worker.js"

account_id = "e6aba92e9aa0421804f64f17b0e07e26"

[dev]
ip = "127.0.0.1"
port = 8787

[[d1_databases]]
binding = "DB"
database_name = "smoke"
database_id = "c41273d8-c3e2-428f-99da-8535af429287"

[observability.logs]
enabled = true